name: learn-github-actions
on: 
   push:
        branches:
          - master

jobs:
  BuildFramework:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build UnitTestSample
      run: ./build.sh

